# InfoMetis v0.5.0 - Apache Flink Ingress Configuration
# Provides HTTP access to Flink Web UI via Traefik on port 8083

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flink-ingress
  namespace: infometis
  labels:
    app: flink-jobmanager
    app.kubernetes.io/part-of: infometis
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.entrypoints: flink
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: flink-jobmanager-service
            port:
              number: 8081