# InfoMetis v0.5.0 - Alertmanager Kubernetes Deployment
# Prometheus Alertmanager for alert management and routing

apiVersion: v1
kind: Namespace
metadata:
  name: infometis
  labels:
    app.kubernetes.io/name: infometis
---
# Alertmanager PersistentVolume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: alertmanager-pv
  labels:
    app.kubernetes.io/part-of: infometis
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  hostPath:
    path: /tmp/alertmanager-data
  persistentVolumeReclaimPolicy: Delete
---
# Alertmanager Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: infometis
  labels:
    app: alertmanager
    app.kubernetes.io/part-of: infometis
data:
  alertmanager.yml: |
    global:
      smtp_smarthost: 'localhost:587'
      smtp_from: 'infometis@localhost'

    route:
      group_by: ['alertname', 'cluster', 'service']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 1h
      receiver: 'web.hook'
      routes:
      - match:
          severity: critical
        receiver: 'critical-alerts'

    receivers:
    - name: 'web.hook'
      webhook_configs:
      - url: 'http://localhost:5001/webhook'
        send_resolved: true

    - name: 'critical-alerts'
      webhook_configs:
      - url: 'http://localhost:5001/webhook/critical'
        send_resolved: true

    inhibit_rules:
    - source_match:
        severity: 'critical'
      target_match:
        severity: 'warning'
      equal: ['alertname', 'cluster', 'service']
---
# Alertmanager Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: infometis
  labels:
    app: alertmanager
    app.kubernetes.io/part-of: infometis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
        app.kubernetes.io/part-of: infometis
    spec:
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
      initContainers:
      - name: alertmanager-data-permission-fix
        image: busybox:1.35
        imagePullPolicy: Never
        command: ['chown', '-R', '65534:65534', '/alertmanager']
        volumeMounts:
        - name: alertmanager-storage
          mountPath: /alertmanager
        securityContext:
          runAsUser: 0
      containers:
      - name: alertmanager
        image: prom/alertmanager:v0.25.1
        imagePullPolicy: Never
        ports:
        - containerPort: 9093
          name: web
        args:
          - --config.file=/etc/alertmanager/alertmanager.yml
          - --storage.path=/alertmanager
          - --web.external-url=http://localhost/alertmanager
          - --web.route-prefix=/
        volumeMounts:
        - name: alertmanager-config
          mountPath: /etc/alertmanager/
        - name: alertmanager-storage
          mountPath: /alertmanager
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        livenessProbe:
          httpGet:
            path: /-/healthy
            port: 9093
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /-/ready
            port: 9093
          initialDelaySeconds: 30
          periodSeconds: 5
      volumes:
      - name: alertmanager-config
        configMap:
          name: alertmanager-config
      - name: alertmanager-storage
        persistentVolumeClaim:
          claimName: alertmanager-storage-claim
---
# Alertmanager Service
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-service
  namespace: infometis
  labels:
    app: alertmanager
    app.kubernetes.io/part-of: infometis
spec:
  type: ClusterIP
  ports:
  - port: 9093
    targetPort: 9093
    protocol: TCP
    name: web
  selector:
    app: alertmanager
---
# Alertmanager Storage PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alertmanager-storage-claim
  namespace: infometis
  labels:
    app: alertmanager
    app.kubernetes.io/part-of: infometis
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 2Gi